"""Category definitions and exemplars for ML classification."""

# Available categories in Apify Store
CATEGORIES = [
    "SOCIAL_MEDIA",
    "AI",
    "AGENTS",
    "LEAD_GENERATION",
    "ECOMMERCE",
    "SEO_TOOLS",
    "JOBS",
    "MCP_SERVERS",
    "NEWS",
    "REAL_ESTATE",
    "DEVELOPER_TOOLS",
    "TRAVEL",
    "VIDEOS",
    "AUTOMATION",
    "INTEGRATIONS",
    "OPEN_SOURCE",
    "OTHER",
]

# Exemplar descriptions for each category - used for semantic similarity matching
CATEGORY_EXEMPLARS = {
    "AGENTS": [
        "Autonomous AI agent powered by GPT-4 or Claude that reasons about complex tasks and makes intelligent decisions without human intervention",
        "LLM-based agent with tool calling capabilities that can browse websites, execute code, send emails, and interact with external APIs autonomously",
        "AI assistant that uses chain-of-thought reasoning to break down goals into subtasks and execute multi-step workflows independently",
        "Intelligent agent with function calling that orchestrates multiple tools and services to accomplish user objectives",
        "MCP server implementing Model Context Protocol that exposes tools for AI agents like Claude Desktop or Cursor to call",
        "Agentic AI system that autonomously plans, reasons, and takes action to complete complex real-world tasks",
        "Browser automation agent powered by large language models that can navigate websites and perform actions based on natural language instructions",
        "AI workflow orchestrator that uses reasoning and tool use to automate complex business processes end-to-end",
    ],
    "AI": [
        "Machine learning model for data analysis and prediction",
        "Natural language processing tool for text understanding",
        "AI-powered content generation and summarization",
        "Computer vision and image recognition service",
        "Large language model integration for text processing",
    ],
    "SOCIAL_MEDIA": [
        "Extract data from social media platforms like Facebook, Instagram, Twitter",
        "Scrape posts, comments, likes, and engagement metrics from social networks",
        "Download videos, images, and media from social platforms",
        "Collect user profiles, followers, and connections from social sites",
        "Monitor social media mentions and hashtags",
    ],
    "LEAD_GENERATION": [
        "Find business contacts, emails, and phone numbers",
        "Extract company information and decision maker details",
        "Generate sales leads from business directories",
        "Collect prospect data for marketing campaigns",
        "Build targeted contact lists for outreach",
    ],
    "ECOMMERCE": [
        "Scrape product data, prices, and reviews from online stores",
        "Monitor competitor pricing and inventory levels",
        "Extract product catalogs from e-commerce websites",
        "Track price changes and stock availability",
        "Collect product specifications and descriptions from retail sites",
    ],
    "SEO_TOOLS": [
        "Analyze website SEO metrics and rankings",
        "Extract backlinks and domain authority data",
        "Monitor keyword positions in search results",
        "Audit website technical SEO issues",
        "Scrape SERP data and search engine results",
    ],
    "JOBS": [
        "Scrape job listings and employment opportunities",
        "Extract job descriptions and requirements",
        "Monitor job boards for new postings",
        "Collect salary and compensation data",
        "Aggregate job listings from multiple sources",
    ],
    "MCP_SERVERS": [
        "Model Context Protocol server for AI tool integration",
        "MCP-compatible API endpoint for LLM applications",
        "Tool server exposing functionality via MCP protocol",
        "AI agent tool provider using Model Context Protocol",
        "MCP server for connecting AI models to external services",
    ],
    "NEWS": [
        "Scrape news articles and headlines",
        "Monitor news sources for specific topics",
        "Extract press releases and media coverage",
        "Aggregate news from multiple publications",
        "Track breaking news and current events",
    ],
    "REAL_ESTATE": [
        "Scrape property listings and real estate data",
        "Extract home prices, addresses, and property details",
        "Monitor housing market trends and listings",
        "Collect rental property information",
        "Aggregate real estate listings from multiple sources",
    ],
    "DEVELOPER_TOOLS": [
        "Code analysis and repository scraping tools",
        "API testing and monitoring utilities",
        "Development workflow automation",
        "Technical documentation extraction",
        "Developer productivity and debugging tools",
    ],
    "TRAVEL": [
        "Scrape hotel prices and availability",
        "Extract flight information and booking data",
        "Monitor travel deals and discounts",
        "Collect restaurant and attraction reviews",
        "Aggregate travel information from booking sites",
    ],
    "VIDEOS": [
        "Download and extract video content",
        "Scrape video metadata and descriptions",
        "Extract video transcripts and captions",
        "Monitor video platforms for new content",
        "Collect video statistics and engagement data",
    ],
    "AUTOMATION": [
        "Automate repetitive web tasks and workflows",
        "Schedule and run automated processes",
        "Form filling and data entry automation",
        "Browser automation for routine tasks",
        "Workflow orchestration and task scheduling",
    ],
    "INTEGRATIONS": [
        "Connect and sync data between platforms",
        "API integration and data transformation",
        "Webhook handling and event processing",
        "Data pipeline and ETL automation",
        "Cross-platform data synchronization",
    ],
    "OPEN_SOURCE": [
        "Open source project and repository tools",
        "Community-contributed automation scripts",
        "Free and open tools for developers",
        "GitHub and GitLab integration tools",
        "Open source data extraction utilities",
    ],
    "OTHER": [
        "General purpose web scraping and automation",
        "Miscellaneous data extraction tools",
        "Utility tools for various purposes",
        "Custom automation solutions",
        "Specialized niche tools",
    ],
}

# Human-readable category names for display
CATEGORY_DISPLAY_NAMES = {
    "SOCIAL_MEDIA": "Social Media",
    "AI": "AI",
    "AGENTS": "Agents",
    "LEAD_GENERATION": "Lead Generation",
    "ECOMMERCE": "E-commerce",
    "SEO_TOOLS": "SEO Tools",
    "JOBS": "Jobs",
    "MCP_SERVERS": "MCP Servers",
    "NEWS": "News",
    "REAL_ESTATE": "Real Estate",
    "DEVELOPER_TOOLS": "Developer Tools",
    "TRAVEL": "Travel",
    "VIDEOS": "Videos",
    "AUTOMATION": "Automation",
    "INTEGRATIONS": "Integrations",
    "OPEN_SOURCE": "Open Source",
    "OTHER": "Other",
}
